# Generated by Django 4.1.2 on 2022-11-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, verbose_name='country_name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('capital', models.CharField(blank=True, max_length=255, verbose_name='capital')),
                ('country_area', models.CharField(blank=True, max_length=255, verbose_name='country_area')),
                ('country_population', models.CharField(blank=True, max_length=255, verbose_name='country_population')),
                ('country_currency', models.CharField(blank=True, max_length=255, verbose_name='country_currency')),
                ('about_country', models.TextField(blank=True, null=True, verbose_name='about_country')),
                ('energe_info', models.TextField(blank=True, null=True, verbose_name='energe_info')),
                ('country_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_description', models.TextField(blank=True, null=True, verbose_name='photo_description')),
                ('country_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description_1', models.TextField(blank=True, null=True, verbose_name='photo_description_1')),
                ('country_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description_2', models.TextField(blank=True, null=True, verbose_name='photo_description_2')),
                ('country_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description_3', models.TextField(blank=True, null=True, verbose_name='photo_description_3')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='year')),
                ('regions', models.CharField(blank=True, max_length=255, null=True, verbose_name='regions')),
                ('plant_name', models.CharField(max_length=255, null=True, verbose_name='plant_name')),
                ('energies_category', models.CharField(max_length=255, null=True, verbose_name='energies_category')),
                ('energy', models.CharField(max_length=255, null=True, verbose_name='energy')),
                ('capacity', models.FloatField(null=True, verbose_name='capacity')),
                ('measuring_unit', models.CharField(max_length=255, null=True, verbose_name='unit')),
                ('energy_generation', models.FloatField(null=True, verbose_name='electricity_generation')),
                ('measuring_unit_generation', models.CharField(max_length=255, null=True, verbose_name='unit')),
                ('Unit_name', models.CharField(max_length=255, null=True, verbose_name='Unit name')),
                ('type_of_ownership', models.CharField(max_length=255, null=True, verbose_name='Type of ownership')),
                ('operator', models.CharField(max_length=255, null=True, verbose_name='Operator')),
                ('cost_ofenergy', models.CharField(max_length=255, null=True, verbose_name='cost_of_energy')),
                ('country_name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.country')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Table name')),
                ('table_country', models.CharField(max_length=255, null=True, verbose_name='table_country')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('energy_type', models.CharField(max_length=255, null=True, verbose_name='energy_type')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('table_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description', models.TextField(blank=True, null=True, verbose_name='photo_description')),
                ('table_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description_1', models.TextField(blank=True, null=True, verbose_name='photo_description_1')),
                ('table_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_description_2', models.TextField(blank=True, null=True, verbose_name='photo_description_2')),
                ('source', models.TextField(blank=True, null=True, verbose_name='source')),
                ('country', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.country', verbose_name='country_name')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='pages.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.table', verbose_name='Table name'),
        ),
    ]
