# Generated by Django 4.1.2 on 2022-10-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сountry', models.CharField(max_length=255, verbose_name='Country')),
                ('regions', models.CharField(max_length=255, verbose_name='regions')),
                ('plant_name', models.CharField(max_length=255, verbose_name='plant_name')),
                ('energies_category', models.CharField(max_length=255, verbose_name='energies_category')),
                ('energy', models.CharField(max_length=255, verbose_name='energy')),
                ('capacity', models.CharField(max_length=255, verbose_name='capacity')),
                ('energy_generation', models.CharField(max_length=255, verbose_name='electricity_generation')),
                ('Unit_name', models.CharField(max_length=255, verbose_name='Unit name')),
                ('type_of_ownership', models.CharField(max_length=255, verbose_name='Type of ownership')),
                ('operator', models.CharField(max_length=255, verbose_name='Operator')),
                ('cost_ofenergy', models.CharField(max_length=255, verbose_name='cost_of_energy')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tables name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='pages.items', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.tables', verbose_name='Таблица'),
        ),
    ]
