# Generated by Django 4.1.2 on 2022-10-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
    ]
