# Generated by Django 4.1.2 on 2022-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_items_item_rename_tables_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Unit_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Unit name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='capacity',
            field=models.CharField(max_length=255, null=True, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_ofenergy',
            field=models.CharField(max_length=255, null=True, verbose_name='cost_of_energy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energies_category',
            field=models.CharField(max_length=255, null=True, verbose_name='energies_category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energy',
            field=models.CharField(max_length=255, null=True, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energy_generation',
            field=models.CharField(max_length=255, null=True, verbose_name='electricity_generation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='operator',
            field=models.CharField(max_length=255, null=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='item',
            name='plant_name',
            field=models.CharField(max_length=255, null=True, verbose_name='plant_name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='regions',
            field=models.CharField(max_length=255, null=True, verbose_name='regions'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_of_ownership',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of ownership'),
        ),
    ]
