# Generated by Django 4.1.2 on 2022-10-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_country_slug_alter_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='energe_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='regions'),
        ),
    ]
