# Generated by Django 4.1.2 on 2022-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_country_energe_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='slug',
            new_name='slug_country',
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_photo_9',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='energe_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Information_about_energe'),
        ),
        migrations.AlterField(
            model_name='item',
            name='capacity',
            field=models.FloatField(null=True, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energy',
            field=models.FloatField(null=True, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Table name'),
        ),
    ]
