# Generated by Django 4.1.2 on 2022-11-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_slug_country_slug_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='energy',
            field=models.CharField(max_length=255, null=True, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energy_generation',
            field=models.FloatField(null=True, verbose_name='electricity_generation'),
        ),
    ]
