# Generated by Django 4.1.2 on 2022-11-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_item_energy_alter_item_energy_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='slug_country',
            new_name='slug',
        ),
    ]
