# Generated by Django 4.1.2 on 2022-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_slug_country_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=255, verbose_name='Country name'),
        ),
    ]
