# Generated by Django 4.1.2 on 2022-11-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_country_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_photo_4',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_photo_5',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_photo_6',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_photo_7',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_photo_8',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_photo_9',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_photo_3',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_photo_4',
        ),
        migrations.AddField(
            model_name='table',
            name='photo_description',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description'),
        ),
        migrations.AddField(
            model_name='table',
            name='photo_description_1',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description_1'),
        ),
        migrations.AddField(
            model_name='table',
            name='photo_description_2',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description_2'),
        ),
        migrations.AddField(
            model_name='table',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_currency',
            field=models.CharField(blank=True, max_length=255, verbose_name='energe_info'),
        ),
        migrations.AlterField(
            model_name='country',
            name='energe_info',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
