# Generated by Django 4.1.2 on 2022-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_country_country_photo_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='photo_description',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description'),
        ),
        migrations.AddField(
            model_name='country',
            name='photo_description_1',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description_1'),
        ),
        migrations.AddField(
            model_name='country',
            name='photo_description_2',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description_2'),
        ),
        migrations.AddField(
            model_name='country',
            name='photo_description_3',
            field=models.TextField(blank=True, null=True, verbose_name='photo_description_3'),
        ),
        migrations.AlterField(
            model_name='table',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='source'),
        ),
    ]
