# Generated by Django 4.1.2 on 2022-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_country_photo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about_country',
            field=models.TextField(blank=True, null=True, verbose_name='about_country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_currency',
            field=models.CharField(blank=True, max_length=255, verbose_name='country_currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='energe_info',
            field=models.TextField(blank=True, null=True, verbose_name='energe_info'),
        ),
    ]
